### ISSUE TITLE
Contact Page update

### ISSUE THREAD

**Issue by ZEviod** [ZEviod/Personal-finance-management#7]
We need to implement a contact page in our Next.js application. This page will allow users to reach out to us directly.

Tasks:

Form Fields:
Full Name (input, required)
Email Address (input, required, email format validation)
Message (textarea, required)

Styling:
Ensure the page is styled appropriately to match the existing application theme (using CSS Modules or styled-components).
Accessibility:
Ensure all form elements are accessible (correct labeling, focus management).

**Comment by Jay-Shah0** [comment]
Can i work on this under hacktoberfest?

**Comment by Jay-Shah0** [comment]
Thanks i got my first PR review under hacktoberfest!!
![image](https://github.com/user-attachments/assets/e98f2a3f-cd22-42e1-a6c0-6a4acad1293c)

**Comment by AdityaInnovates** [comment]
Hello, @ZEviod, I'd be happy to help with this. Please assign me the task.

**Comment by ZEviod** [comment]
okay i will assign this task to you @AdityaInnovates !
you can fork the repository and start working, following the procedure
